### ISSUE TITLE
How can I cite your ICCV version of the article?

### ISSUE THREAD

**Issue by Breeze-Zero** [ChrisMats/medical_transformers#2]
Thank you very much for your work. I would like to quote your article, but for the sake of formality, I would rather quote ICCV than arxiv.

**Comment by ChrisMats** [comment]
Thank you for your kind words. We are happy to see that you find our work interesting.
I talked with the conference organisers and they confirm that the best way to cite our work is to cite the arxiv version.

@article{matsoukas2021time,
  title={Is it time to replace cnns with transformers for medical images?},
  author={Matsoukas, Christos and Haslum, Johan Fredin and S{\"o}derberg, Magnus and Smith, Kevin},
  journal={arXiv preprint arXiv:2108.09038},
  year={2021}
}

If you want you can also add the workshop link (https://sites.google.com/view/cvamd2021/program) which includes the paper.
However, I am not sure for how long this link will be valid.
