### ISSUE TITLE
fine tune dino

### ISSUE THREAD

**Issue by byte-dance** [ChrisMats/medical_transformers#3]
how can I perform fine tune after self-supervised pretraining with dino? i.e which command and args should I set?

**Comment by ChrisMats** [comment]
Hi,
To do that, please turn on the 'use_pretrained' flag from the json file (transfer_learning_params.use_pretrained=true). Then give the name of the pre-trained model that you want to use (transfer_learning_params. pretrained_model_name). If your pretrained model's checkpoint is not lacated at training_params.save_dir then, please define the dir of your checkpoint at transfer_learning_params. pretrained_path
