### ISSUE TITLE
Train with cnn_models

### ISSUE THREAD

**Issue by huaiyi66** [ChrisMats/medical_transformers#6]
how can I  train model with ResNet50? i.e which command and args should I set?

**Comment by ChrisMats** [comment]
Hi,
All you need to do is to change the backbone type in model params
https://github.com/ChrisMats/medical_transformers/blob/ecd460a66ea2b03a83caf4c94546ef012e17e049/params.json#L122

**Comment by huaiyi66** [comment]
> Hi, All you need to do is to change the backbone type in model params
> 
> https://github.com/ChrisMats/medical_transformers/blob/ecd460a66ea2b03a83caf4c94546ef012e17e049/params.json#L122
Thank you so much！！
